
# CA

```{r}
par(mfrow=c(1,1))

tt<-table(df[,c("f.cost","period")])
tt
chisq.test(tt) # Independency? H0: Rows and columns are independent g.ll (4-1)*(4-1)=9 pvalue 0.01 < 0.05 H0 Reject (not far from independency)

res.ca<-CA(tt)
#lines(res.ca$row$coord[,1],res.ca$row$coord[,2],lwd=2,col="blue")

summary(res.ca,dig=2)
names(res.ca)
fviz_eig(res.ca)

fviz_ca_biplot(res.ca,repel=TRUE)+theme_bw()

tt<-table(df[,c("f.cost","f.tt")])
tt
res.ca<-CA(tt)
#lines(res.ca$row$coord[,1],res.ca$row$coord[,2],lwd=2,col="blue")
summary(res.ca)
chisq.test(tt)

plot(res.ca$row$coord[,1],res.ca$row$coord[,2],pch=19,col="blue",xlim=c(-1.5,1.5),ylim=c(-1,1),xlab="Axis 1",ylab="Axis 2",main="CA f.cost vs f.tt")
points(res.ca$col$coord[,1],res.ca$col$coord[,2],pch=19,lwd=2,col="red")
text(res.ca$row$coord[,1],res.ca$row$coord[,2],col="blue",labels=levels(df$f.cost))
text(res.ca$col$coord[,1],res.ca$col$coord[,2],col="red",labels=levels(df$f.tt))
lines(res.ca$row$coord[,1],res.ca$row$coord[,2],lwd=2,col="blue")
lines(res.ca$col$coord[,1],res.ca$col$coord[,2],lwd=2,col="red")

summary(res.ca)
mean(res.ca$eig[,1])  # Kaiser: how many dimensions to retain

# Traditional analysis by contingency tables
prop.table(tt,1);prop.table(table(df$f.tt))
prop.table(tt,2);prop.table(table(df$f.cost))
chisq.test(tt)
```



# MCA using multivariant

```{r}
## Hobbies example
data(hobbies)
summary(hobbies)
res.mca <- MCA(hobbies,quali.sup=19:22,quanti.sup=23)
plot(res.mca,invisible=c("ind","quali.sup"),hab="quali") 
plot(res.mca,invisible=c("var","quali.sup"),cex=.5,label="none") 
plot(res.mca,invisible=c("ind","var"),hab="quali")
names(res.mca)
```


```{r}
par(mfrow=c(1,1))

#llvout<-which(df$mvout==TRUE);length(llvout)
#res.mca<-MCA(df[,c(vars_dis,"Total_amount")],quali.sup=c(5,14),quanti.sup=19,ind.sup=llvout)
vars_dis
res.mca<-MCA(df[,c(vars_dis,"Total_amount")],quali.sup=c(5,14),quanti.sup=19,ncp=29)
names(res.mca)
summary(res.mca,nbelements=50,nbind=0)
mean(res.mca$eig[,1]) # Indica fins dim 29 o criteri Inercia explicada 80% ?s 30

# Individual Representation
plot.MCA(res.mca,choix=c("ind"),cex=0.8)
plot.MCA(res.mca,choix=c("ind"),invisible=c("ind"),cex=0.8)

# Representation of categories
plot.MCA(res.mca,choix=c("ind"),invisible=c("ind"),axes=c(1,2))
#lines(res.mca$var$coord[11:14,1],res.mca$var$coord[11:14,2],lwd=1,col="black") # Speed
#lines(res.mca$quali.sup$coord[3:6,1],res.mca$quali.sup$coord[3:6,2],lwd=2,col="darkgreen")
names(res.mca)
res.mca$var
plot.MCA(res.mca,choix=c("ind"),invisible=c("ind"),axes=c(3,4))
plot.MCA(res.mca,choix=c("var"),axes=c(3,4))

# Use modern ggplot facilities
names(res.mca)
fviz_eig(res.mca,ncp=40)
fviz_cos2(res.mca, choice = "var", axes = 1:2)+theme_bw()
fviz_contrib(res.mca, choice = "var", axes = 1:2)+theme_bw()
fviz_mca_var(res.mca, col.var="cos2",repel=TRUE,labelsize = 2)+
    scale_color_gradient2(low="green", mid="blue", 
    high="red", midpoint=0.75)+theme_bw()

fviz_mca_biplot(res.mca, invisible="ind",axes=1:2,repel=FALSE,labelsize = 2)+theme_bw()
#fviz_mca_biplot(res.mca, axes=1:2,repel=TRUE,arrows=c(TRUE,FALSE))+theme_bw()  # No ho feu
```

# Synthesis through HCPC: Hierarchical Clustering

```{r}
###
### Clustering the individuals
### Before, hou have to perform a PCA with the number of axes 
### that you have decided to take into account (indicated through ncp=)
?HCPC
#res.mca<-MCA(df[,c(vars_dis,"Total_amount")],quali.sup=c(5,14),quanti.sup=19,ncp=29,ind.sup=llvout)
res.mca<-MCA(df[,c(vars_dis,"Total_amount")],quali.sup=c(5,14),quanti.sup=19,ncp=29)
res.hcpc<-HCPC(res.mca,nb.clust=-1,order=TRUE)
names(res.hcpc)

names(res.hcpc$call$t)
res.hcpc$call$t$within[1:8]
(res.hcpc$call$t$within[1]-res.hcpc$call$t$within[1:15])/res.hcpc$call$t$within[1]

df$claHP<-9
df[row.names(res.hcpc$data.clust),"claHP"]<-res.hcpc$data.clust$clust
df$claHP<-factor(df$claHP)
summary(res.hcpc$data.clust$clust)
table(df$claHP)

### Interpret clustering results
summary(res.hcpc$data.clust$clust)

#Block A: res.hcpc$desc.var
#Block B: res.hcpc$desc.axes
#Block C: res.hcpc$desc.ind


### desc.var ###
### A. The description of the clusters by the variables ###
names(res.hcpc$desc.var)
res.hcpc$desc.var
### desc.var$test.chi2 ###
### A.1. The categorical variables which characterizes the clusters ###
res.hcpc$desc.var$test.chi2

### desc.var$category ###
### A.2. The description of each cluster by the categories ##
res.hcpc$desc.var$category

### desc.var$quanti.var ###
### A.3. The quantitative variables which characterizes the clusters ###
res.hcpc$desc.var$quanti.var

### desc.var$quanti ###
### A.4. The description of each cluster by the quantitative variables ###
res.hcpc$desc.var$quanti

### desc.axes ###

### desc.ind ###
### C. The description of the clusters by the individuals ###
names(res.hcpc$desc.ind)
res.hcpc$desc.ind$para
res.hcpc$desc.ind$dist

#### Characteristic individuals
para1<-which(rownames(res.mca$ind$coord)%in%names(res.hcpc$desc.ind$para[[1]]))
para2<-which(rownames(res.mca$ind$coord)%in%names(res.hcpc$desc.ind$para[[2]]))
para3<-which(rownames(res.mca$ind$coord)%in%names(res.hcpc$desc.ind$para[[3]]))
# to be completed...

#plot(res.mca,label="none",invisible=c("quali","ind.sup"))
#points(res.mca$ind$coord[para1,1],res.mca$ind$coord[para1,2],col="magenta",cex=2,pch=16)

# Dendrogram
fviz_dend(res.hcpc, show_labels = FALSE)
# Individuals factor map
fviz_cluster(res.hcpc, geom = "point", main = "Factor map")

res.mca<-MCA(df[,c(vars_dis,"Total_amount","claHP")],quali.sup=c(5,14,20),quanti.sup=19,ncp=29)
fviz_mca_ind(res.mca, 
             label = "none", invisible=c("ind.sup"),# hide individual labels
             habillage = "claHP", # color by groups 
             addEllipses = TRUE, ellipse.type = "confidence",
             ggtheme = theme_bw()) 
```

# Kmeans: Partitioning in k=8 groups
```{r}
res.mca<-MCA(df[,c(vars_dis,"Total_amount")],quali.sup=c(5,14),quanti.sup=19,ncp=29)
summary(res.mca)
ppcc<-res.mca$ind$coord[,1:29]
dim(ppcc)
kc<-kmeans(dist(ppcc),8, iter.max = 30, trace=T)

df[names(kc$cluster),"claKM"]<-kc$cluster
kc$betweenss/kc$totss

```